In [ ]:
import numpy as np

In [7]:
#Broadcasting in NumPy-(Make differently shaped arrays compatible for the operation.)

#Broadcasting with a 1D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

bonus=np.array([1,2,3])
result=arr+bonus
print(result)


#Broadcasting with a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr + 12)

[[11 22 33]
 [41 52 63]
 [71 82 93]]
[[13 14 15]
 [16 17 18]
 [19 20 21]]
