In [ ]:
import numpy as np

In [4]:
#Vectorization in NumPy-(Vectorization means performing an operation on an entire NumPy array at once, without writing a Python for loop.)
arr=np.array([1,2,3,4,5,6])
result=[]
result=arr**2
print(result)
result = arr + 5
print(result)

#Vectorization with two arrays
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c=a+b
print(c)

[ 1  4  9 16 25 36]
[ 6  7  8  9 10 11]
[11 22 33]
